"""
Generates seed.sql from nutrition-tracker/data/dishes.json.

Run whenever dishes.json changes (i.e. whenever build_dishes.py has been
rerun in the data-building phase of this project) to regenerate the D1 seed
data. This script only reads dishes.json and writes seed.sql -- it does not
touch the database itself; that's a separate `wrangler d1 execute` step,
kept separate so the SQL can be reviewed before it's applied.
"""
import json
import re
from pathlib import Path

APP_DIR = Path(__file__).parent.parent
DATA_DIR = APP_DIR.parent / "data"


def sql_str(value):
    """Single-quote a string for SQL, escaping embedded single quotes."""
    if value is None:
        return "NULL"
    escaped = str(value).replace("'", "''")
    return f"'{escaped}'"


def sql_num(value):
    if value is None:
        return "NULL"
    return repr(value)


def main():
    with open(DATA_DIR / "dishes.json") as f:
        data = json.load(f)

    dishes = data["dishes"]
    lines = [
        "-- Generated by scripts/generate_seed.py from nutrition-tracker/data/dishes.json.",
        "-- Do not hand-edit -- rerun the generator instead.",
        "--",
        "-- Uses INSERT OR REPLACE, not DELETE + INSERT: the logs table has a",
        "-- foreign key to dishes(dish_id), so once any real log exists (i.e.",
        "-- always, after launch), a DELETE FROM dishes fails with a foreign",
        "-- key constraint violation. REPLACE updates existing rows in place --",
        "-- safe to rerun any time dishes.json changes (which happens whenever",
        "-- a dish's numbers get corrected -- this has happened repeatedly across",
        "-- this project's data-building phase, and will keep happening).",
        "",
    ]

    for dish_id, d in dishes.items():
        p100 = d["per_100g"]
        presets = d.get("portion_presets")
        presets_json = sql_str(json.dumps(presets)) if presets else "NULL"

        values = [
            sql_str(dish_id),
            sql_str(d["category"]),
            sql_str(d["serving_label"]),
            sql_num(d["default_serving_g"]),
            sql_num(p100["kcal"]),
            sql_num(p100["protein_g"]),
            sql_num(p100["carbs_g"]),
            sql_num(p100["fat_g"]),
            sql_num(p100["fiber_g"]),
            sql_num(p100["sugar_g"]),
            sql_num(p100["sodium_mg"]),
            presets_json,
        ]
        lines.append(
            "INSERT OR REPLACE INTO dishes (dish_id, category, serving_label, default_serving_g, "
            "per_100g_kcal, per_100g_protein_g, per_100g_carbs_g, per_100g_fat_g, "
            "per_100g_fiber_g, per_100g_sugar_g, per_100g_sodium_mg, portion_presets_json) "
            f"VALUES ({', '.join(values)});"
        )

    out_path = APP_DIR / "scripts" / "seed.sql"
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {len(dishes)} INSERT statements to {out_path}")


if __name__ == "__main__":
    main()
