import { createRequestHandler } from "react-router";
// @ts-expect-error - generated by `react-router build`, not present until build time
import * as build from "../build/server/index.js";
import type { Env } from "../app/shopify.server";

declare module "react-router" {
  interface AppLoadContext {
    cloudflare: { env: Env; ctx: ExecutionContext };
  }
}

const requestHandler = createRequestHandler(build, "production");

export default {
  async fetch(request, env, ctx) {
    return requestHandler(request, {
      cloudflare: { env, ctx },
    });
  },
} satisfies ExportedHandler<Env>;
