-- Dishes: seeded from nutrition-tracker/data/dishes.json (generated by build_dishes.py).
-- One row per dish. per_100g_* columns let the app scale to any portion the
-- user actually logs; default_serving_g is the recipe's own typical serving.
CREATE TABLE dishes (
  dish_id TEXT PRIMARY KEY,
  category TEXT NOT NULL,
  serving_label TEXT NOT NULL,
  default_serving_g REAL NOT NULL,
  per_100g_kcal REAL NOT NULL,
  per_100g_protein_g REAL NOT NULL,
  per_100g_carbs_g REAL NOT NULL,
  per_100g_fat_g REAL NOT NULL,
  per_100g_fiber_g REAL NOT NULL,
  per_100g_sugar_g REAL NOT NULL,
  per_100g_sodium_mg REAL NOT NULL,
  -- JSON-encoded {preset_name: {grams, kcal, protein_g, ...}} or NULL if the
  -- dish has no named portion sizes. Kept as JSON rather than a join table
  -- since presets are read whole, never queried by field.
  portion_presets_json TEXT
);

CREATE INDEX idx_dishes_category ON dishes(category);

-- One row per logged food item. A single user message ("chicken karahi and
-- two rotis") produces multiple rows here, one per item Gemini identified --
-- see parseLog.ts's array-of-entries design.
CREATE TABLE logs (
  id TEXT PRIMARY KEY, -- UUID, generated by the Worker
  device_id TEXT NOT NULL, -- no-login MVP: identifies a user by device, not an account
  dish_id TEXT NOT NULL REFERENCES dishes(dish_id),
  free_text_description TEXT, -- only set when dish_id is 'none_of_these'
  quantity REAL NOT NULL DEFAULT 1,
  resolved_grams REAL NOT NULL, -- the actual portion size used for this log, after presets/custom_grams/quantity resolution
  swaps_json TEXT, -- JSON-encoded {flour, protein_cut, fat, dairy} of swaps actually applied, or NULL
  -- Nutrition is stored per-log, not derived by re-joining dishes at read
  -- time -- if a dish's numbers are corrected later (as has happened
  -- repeatedly across the data-building phase of this project), historical
  -- logs stay accurate to what was true when they were logged.
  kcal REAL NOT NULL,
  protein_g REAL NOT NULL,
  carbs_g REAL NOT NULL,
  fat_g REAL NOT NULL,
  fiber_g REAL NOT NULL,
  sugar_g REAL NOT NULL,
  sodium_mg REAL NOT NULL,
  logged_at INTEGER NOT NULL, -- unix seconds, when the user says they ate it
  created_at INTEGER NOT NULL -- unix seconds, when the row was written
);

CREATE INDEX idx_logs_device_date ON logs(device_id, logged_at);
